services:
  frontend:
    build:
      context: ./esc-voting-web
    ports:
      - "80:80"
    depends_on:
      - php
    restart: unless-stopped

  php:
    build:
      context: ./esc-voting-service
    volumes:
      - ./esc-voting-service/config/jwt:/var/www/symfony/config/jwt:ro
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?serverVersion=16&charset=utf8
      JWT_SECRET_KEY: /var/www/symfony/config/jwt/private.pem
      JWT_PUBLIC_KEY: /var/www/symfony/config/jwt/public.pem
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}
      CORS_ALLOW_ORIGIN: ".*"
      MESSENGER_TRANSPORT_DSN: doctrine://default?auto_setup=0
      MAILER_DSN: null://null
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${DB_NAME}", "-U", "${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db_data:
