server {
    listen 80;
    server_name escvoting.fr www.escvoting.fr;
    return 301 https://escvoting.fr$request_uri;
}

server {
    listen 443 ssl;
    server_name escvoting.fr www.escvoting.fr;
    client_max_body_size 10M;

    ssl_certificate /etc/nginx/certs/fullchain.cer;
    ssl_certificate_key /etc/nginx/certs/escvoting.fr.key;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~ ^/api {
        fastcgi_pass php:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/symfony/public/index.php;
        fastcgi_param REQUEST_URI $request_uri;
        fastcgi_param DOCUMENT_ROOT /var/www/symfony/public;
        fastcgi_read_timeout 300;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    }
}
